language: csharp
solution: ./DigitalLibraryApplication.sln 
dist: trusty
mono: none
dotnet: 3.0.0
install: 
    - dotnet restore
script:
    - dotnet build
    - dotnet test ./DigitalLibraryUnitTests/DigitalLibraryUnitTests.csproj    
